//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressesView
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public int IdDistrict { get; set; }
        public string SectorName { get; set; }
        public string Postman { get; set; }
    }
}
