//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationsView
    {
        public int Id { get; set; }
        public string PubTitle { get; set; }
        public string PubType { get; set; }
        public string PubIndex { get; set; }
        public int Price { get; set; }
    }
}
